from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from bson import ObjectId
from routes.auth import get_current_user
from database.db import generations_collection
from database.models import Revision

router = APIRouter(prefix="/history", tags=["History & Revisions"])

class NewRevisionInput(BaseModel):
    content: str
    action_type: str = "manual_edit"

@router.get("/my-bids")
async def get_my_history(current_user: dict = Depends(get_current_user)):
    """Fetch all past bids generated by the current user."""
    # Query MongoDB for documents belonging to this user
    cursor = generations_collection.find({"user_id": str(current_user["_id"])})
    
    # Sort by most recent first (-1)
    cursor.sort("created_at", -1)
    
    # Get up to 100 recent bids
    bids = await cursor.to_list(length=100) 
    
    # Convert MongoDB ObjectIds to strings so they can be sent as JSON
    for bid in bids:
        bid["_id"] = str(bid["_id"])
        
    return {"bids": bids}

@router.post("/{generation_id}/revise")
async def add_revision(
    generation_id: str, 
    revision_data: NewRevisionInput, 
    current_user: dict = Depends(get_current_user)
):
    """Save a new edit/revision for a specific bid."""
    try:
        obj_id = ObjectId(generation_id)
    except:
        raise HTTPException(status_code=400, detail="Invalid generation ID format")

    # Create the new revision object
    new_rev = Revision(content=revision_data.content, action_type=revision_data.action_type)
    rev_dict = new_rev.model_dump(mode='json')

    # Update MongoDB by pushing the new revision to the array
    result = await generations_collection.update_one(
        {"_id": obj_id, "user_id": str(current_user["_id"])}, # Ensure they own it!
        {"$push": {"revisions": rev_dict}}
    )

    if result.matched_count == 0:
        raise HTTPException(status_code=404, detail="Bid not found or you don't have permission to edit it.")

    return {"message": "Revision saved successfully!", "revision": rev_dict}