import logging
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from bson import ObjectId
from routes.auth import get_current_user
from database.db import generations_collection
from database.models import Revision

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/history", tags=["History & Revisions"])

class NewRevisionInput(BaseModel):
    content: str
    action_type: str = "manual_edit"

class OutcomeUpdate(BaseModel):
    outcome: str

@router.get("/my-bids")
async def get_my_history(current_user: dict = Depends(get_current_user)):
    """Fetch all past bids generated by the current user."""
    try:
        cursor = generations_collection.find({"user_id": str(current_user["_id"])})
        cursor.sort("created_at", -1)
        bids = await cursor.to_list(length=100) 
        
        for bid in bids:
            bid["_id"] = str(bid["_id"])
            
        return {"bids": bids}
    except Exception as e:
        logger.error(f"Database error in get_my_history: {e}")
        raise HTTPException(status_code=500, detail="Could not retrieve history.")

@router.post("/{generation_id}/revise")
async def add_revision(
    generation_id: str, 
    revision_data: NewRevisionInput, 
    current_user: dict = Depends(get_current_user)
):
    """Save a new edit/revision for a specific bid."""
    new_rev = Revision(content=revision_data.content, action_type=revision_data.action_type)
    rev_dict = new_rev.model_dump(mode='json')

    try:
        # Robust query: Support both new MongoDB ObjectIds and older string IDs
        try:
            obj_id = ObjectId(generation_id)
            query = {"$or": [{"_id": obj_id}, {"_id": generation_id}], "user_id": str(current_user["_id"])}
        except Exception:
            query = {"_id": generation_id, "user_id": str(current_user["_id"])}

        result = await generations_collection.update_one(
            query,
            {"$push": {"revisions": rev_dict}}
        )

        if result.matched_count == 0:
            raise HTTPException(status_code=404, detail="Bid not found or access denied.")

        return {"message": "Revision saved successfully!", "revision": rev_dict}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Database error in add_revision: {e}")
        raise HTTPException(status_code=500, detail="Could not save revision.")

@router.put("/{generation_id}/outcome")
async def update_outcome(
    generation_id: str, 
    outcome_data: OutcomeUpdate, 
    current_user: dict = Depends(get_current_user)
):
    """Tag a bid as Won or Lost."""
    # Normalize outcome to handle uppercase/lowercase edge cases
    normalized_outcome = outcome_data.outcome.strip().capitalize()
    
    if normalized_outcome not in ["Won", "Lost"]:
        raise HTTPException(status_code=400, detail="Invalid outcome tag. Use 'Won' or 'Lost'.")

    try:
        # Robust query: Support both new MongoDB ObjectIds and older string IDs
        try:
            obj_id = ObjectId(generation_id)
            query = {"$or": [{"_id": obj_id}, {"_id": generation_id}], "user_id": str(current_user["_id"])}
        except Exception:
            query = {"_id": generation_id, "user_id": str(current_user["_id"])}

        result = await generations_collection.update_one(
            query,
            {"$set": {"outcome_tag": normalized_outcome}}
        )

        if result.matched_count == 0:
            raise HTTPException(status_code=404, detail="Bid not found or access denied.")

        return {"message": f"Bid marked as {normalized_outcome}!"}
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Database error in update_outcome: {e}")
        raise HTTPException(status_code=500, detail="Could not update outcome.")

@router.get("/public/{generation_id}")
async def get_public_proposal(generation_id: str):
    """Public endpoint to fetch a proposal by ID for client sharing."""
    try:
        try:
            obj_id = ObjectId(generation_id)
            query = {"$or": [{"_id": obj_id}, {"_id": generation_id}]}
        except Exception:
            query = {"_id": generation_id}

        doc = await generations_collection.find_one(query)
        if not doc:
            raise HTTPException(status_code=404, detail="Proposal not found.")

        # Get the latest revision or fallback to original content
        if doc.get("revisions") and len(doc["revisions"]) > 0:
            content = doc["revisions"][-1]["content"]
        else:
            content = doc.get("content", "Content unavailable.")

        return {
            "content": content,
            "created_at": doc.get("created_at"),
            "project_category": doc.get("project_category")
        }
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Database error in get_public_proposal: {e}")
        raise HTTPException(status_code=500, detail="Could not retrieve public proposal.")